import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Webxela | Jenkins Personal Portfolio",
  description: "Generated by Jenkins",
  verification: {
    google: "AvADXlpaf5hKEoyC6DJDE-oHlRpgo34Ie0TN_1RaB34",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
    // <>
    //   <Head>
    //     <title>Webxela | Personal Portfolio</title>
    //     <meta name="description" content="Generate by creat next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <Navbar />
    //   <main>{children}</main>
    // </>
  );
}
